services:
  frontend:
    build:
      context: .
    image: vmlc-frontend:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file: .env
    environment:
      - WATCHPACK_POLLING=false
      - CHOKIDAR_USEPOLLING=false
