services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.docker/config.json:/config.json:ro
    environment:
      - DOCKER_CONFIG=/
    networks:
      - prod
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.05'
        reservations:
          memory: 50M
          cpus: '0.02'
  frontend:
    image: ghcr.io/verboheit/vmlc-frontend:prod
    pull_policy: always
    restart: always
    env_file: prod.env
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 384M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      # update_config:
      #     parallelism: 1
      #     delay: 10s
      #     order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
    networks:
      - prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`portal.verbohiet.org`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  traefik:
    image: traefik:v3.5.3
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${COMPOSE_PROJECT_NAME}_prod"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=verboheitconsulting@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--log.level=INFO"
      - "--log.format=json"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - prod_frontend_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - prod
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  prod:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_prod

volumes:
  prod_frontend_letsencrypt: