services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/.docker/config.json:/config.json:ro
    environment:
      - DOCKER_CONFIG=/
    networks:
      - staging
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.05'
        reservations:
          memory: 50M
          cpus: '0.02'
  app:
    image: ghcr.io/verboheit/vmlc-frontend:staging
    pull_policy: always
    restart: unless-stopped
    env_file: staging.env
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 384M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    networks:
      - staging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`staging-portal.verbohiet.org`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=le"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"

  traefik:
    image: traefik:v3.5.3
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${COMPOSE_PROJECT_NAME}_staging"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=verboheitconsulting@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--log.level=INFO"
      - "--log.format=json"
      - "--accesslog=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staging_app_letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - staging
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  staging:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_staging
volumes:
  staging_app_letsencrypt: