services:
  app:
    build:
      context: .
      target: development
    image: vmlc-frontend:dev
    # image: ghcr.io/verboheit/vmlc-frontend:dev
    # pull_policy: always
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file: .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=false
      - CHOKIDAR_USEPOLLING=false
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    networks:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`dev-portal.localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
  traefik:
    image: traefik:v3.5.3
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${COMPOSE_PROJECT_NAME}_dev"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dev
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
networks:
  dev:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_dev

